/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AstroAppDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkFeDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FeAcmCertArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "SupabaseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseVPC": {
      "type": "sst.aws.Vpc"
    }
    "ttn-canarySupabaseVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}